forge 'http://forge.puppetlabs.com'

mod 'maestrodev/maestro_nodes', '>=1.2.5'
mod 'maestrodev/maestro_demo'
mod 'puppetlabs/nodejs',        :git => 'https://github.com/maestrodev/puppetlabs-nodejs.git'
mod 'statsd',                   :git => 'https://github.com/maestrodev/puppet-statsd.git'
mod 'nginx',                    :git => 'https://github.com/jfryman/puppet-nginx.git', :ref => 'e333b4'

# optional modules
#mod 'artifactory',          :git => 'https://github.com/maestrodev/puppet-artifactory.git'
#mod 'bamboo',               :git => 'https://github.com/maestrodev/puppet-bamboo.git'
#mod 'capybara',             :git => 'https://github.com/maestrodev/puppet-capybara.git'
#mod 'continuum',            :git => 'https://github.com/maestrodev/puppet-continuum.git'
#mod 'cucumber',             :git => 'https://github.com/maestrodev/puppet-cucumber.git'
#mod 'flowdock',             :git => 'https://github.com/maestrodev/puppet-flowdock.git'
#mod 'install4j',            :git => 'https://github.com/maestrodev/puppet-install4j.git'
#mod 'jetty',                :git => 'https://github.com/maestrodev/puppet-jetty.git'
#mod 'limits',               :git => 'https://github.com/maestrodev/puppet-limits.git', :ref => 'redhat'
#mod 'mcollective',          :git => 'https://github.com/puppetlabs/puppetlabs-mcollective.git', :ref => '596ca9'
#mod 'maestrodev/perforce',  '1.0.0'
#mod 'subversion_edge',      :git => 'https://github.com/maestrodev/puppet-subversion_edge.git'
