forge 'http://forge.puppetlabs.com'

mod 'activemq',            :git => 'https://github.com/maestrodev/puppet-activemq.git'
mod 'java',                :git => 'https://github.com/maestrodev/puppetlabs-java.git'
mod 'maestro_nodes',       :git => 'https://github.com/maestrodev/puppet-maestro_nodes.git'

# until released
mod 'ant',                 :git => 'https://github.com/maestrodev/puppet-ant.git'
mod 'git',                 :git => 'https://github.com/maestrodev/puppet-git.git'
mod 'svn',                 :git => 'https://github.com/maestrodev/puppet-svn.git'
mod 'jenkins',             :git => 'https://github.com/maestrodev/puppet-jenkins.git'
mod 'maestro',             :git => 'https://github.com/maestrodev/puppet-maestro.git'
mod 'sonar',               :git => 'https://github.com/maestrodev/puppet-sonar.git'
mod 'rvm',                 :git => 'https://github.com/maestrodev/puppet-rvm.git'
mod 'maestro',             :git => 'https://github.com/maestrodev/puppet-maestro.git'

# optional modules
mod 'artifactory',         :git => 'https://github.com/maestrodev/puppet-artifactory.git'
mod 'bamboo',              :git => 'https://github.com/maestrodev/puppet-bamboo.git'
mod 'capybara',            :git => 'https://github.com/maestrodev/puppet-capybara.git'
mod 'continuum',           :git => 'https://github.com/maestrodev/puppet-continuum.git'
mod 'cucumber',            :git => 'https://github.com/maestrodev/puppet-cucumber.git'
mod 'flowdock',            :git => 'https://github.com/maestrodev/puppet-flowdock.git'
mod 'install4j',           :git => 'https://github.com/maestrodev/puppet-install4j.git'
mod 'jetty',               :git => 'https://github.com/maestrodev/puppet-jetty.git'
mod 'limits',              :git => 'https://github.com/maestrodev/puppet-limits.git', :ref => 'redhat'
mod 'mcollective',         :git => 'https://github.com/puppetlabs/puppetlabs-mcollective.git', :ref => '596ca9'
mod 'ntp',                 :git => 'https://github.com/maestrodev/puppet-ntp.git'
mod 'perforce',            :git => 'https://github.com/maestrodev/puppet-perforce.git'
mod 'postgresql',          :git => 'https://github.com/etiennep/puppet-postgresql.git'
mod 'subversion_edge',     :git => 'https://github.com/maestrodev/puppet-subversion_edge.git'
