forge 'http://forge.puppetlabs.com'

mod 'activemq',            :git => 'https://github.com/maestrodev/puppet-activemq.git'

mod 'puppetlabs/java',     '~>0.2.0'
mod 'maestrodev/maestro_nodes'

# optional modules
mod 'artifactory',         :git => 'https://github.com/maestrodev/puppet-artifactory.git'
mod 'bamboo',              :git => 'https://github.com/maestrodev/puppet-bamboo.git'
mod 'capybara',            :git => 'https://github.com/maestrodev/puppet-capybara.git'
mod 'continuum',           :git => 'https://github.com/maestrodev/puppet-continuum.git'
mod 'cucumber',            :git => 'https://github.com/maestrodev/puppet-cucumber.git'
mod 'flowdock',            :git => 'https://github.com/maestrodev/puppet-flowdock.git'
mod 'install4j',           :git => 'https://github.com/maestrodev/puppet-install4j.git'
mod 'jetty',               :git => 'https://github.com/maestrodev/puppet-jetty.git'
mod 'limits',              :git => 'https://github.com/maestrodev/puppet-limits.git', :ref => 'redhat'
mod 'mcollective',         :git => 'https://github.com/puppetlabs/puppetlabs-mcollective.git', :ref => '596ca9'
mod 'ntp',                 :git => 'https://github.com/maestrodev/puppet-ntp.git'
mod 'maestrodev/perforce', '1.0.0'
mod 'subversion_edge',     :git => 'https://github.com/maestrodev/puppet-subversion_edge.git'
mod 'puppetlabs/mongodb'
mod 'puppetlabs/nodejs',   :git => 'https://github.com/maestrodev/puppetlabs-nodejs.git'
mod 'statsd',              :git => 'https://github.com/maestrodev/puppet-statsd.git'
mod 'maestrodev/archiva',  :git => 'https://github.com/maestrodev/puppet-archiva.git'
