---
maestro::repository::username: 'your_username'
maestro::repository::password: 'CHANGEME'

maestro::maestro::version: '4.9.0'
maestro::maestro::package_type: 'rpm'
maestro::maestro::admin_password: 'admin1'
maestro::maestro::master_password: 'maestro'
maestro::maestro::db_server_password: 'maestro'
maestro::maestro::db_password: 'maestro'
maestro::maestro::agent_auto_activate: true

maestro::agent::agent_version: '1.5.0'
maestro::agent::package_type: 'rpm'
maestro::agent::stomp_host: 'localhost'
maestro::agent::agent_name: '%{hostname}'

archiva::version: '1.4-M1-maestro-3.4.3.2'
activemq::max_memory: '64'

# Archiva repository
maestro_nodes::repositories::host: 'localhost'

# Demo compositions configuration
maestro::lucee::demo_compositions::archiva_host: 'localhost'
maestro::lucee::demo_compositions::jenkins_host: 'localhost'
maestro::lucee::demo_compositions::sonar_host: 'localhost'
