---
maestro::repository::username: 'your_username'
maestro::repository::password: 'CHANGEME'

maestro::maestro::version: '4.8.0'
maestro::maestro::package_type: 'rpm'
maestro::maestro::admin_password: 'admin1'
maestro::maestro::master_password: 'maestro'
maestro::maestro::db_server_password: 'maestro'
maestro::maestro::db_password: 'maestro'
maestro::maestro::agent_auto_activate: true

maestro::agent::agent_version: '1.4.1'
maestro::agent::package_type: 'rpm'
maestro::agent::stomp_host: 'localhost'

archiva::version: '1.4-M1-maestro-3.4.3.2'
activemq::max_memory: '64'
