---
# Don't modify these values, they get overwritten in each update
# Copy them to common.yaml or other hiera file specific to some nodes %{clientcert}.yaml
# See Puppet Hiera documentation for more detail on config files

maestro::repository::username: 'your_username'
maestro::repository::password: 'CHANGEME'

maestro::maestro::version: '4.13.0'
maestro::maestro::package_type: 'rpm'
maestro::maestro::admin_password: 'admin1'
maestro::maestro::master_password: 'maestro'
maestro::maestro::db_server_password: 'maestro'
maestro::maestro::db_password: 'maestro'
maestro::maestro::agent_auto_activate: true
maestro::maestro::enabled: true

maestro::agent::agent_version: '1.7.0'
maestro::agent::package_type: 'rpm'
maestro::agent::stomp_host: 'localhost'
maestro::agent::agent_name: '%{hostname}'

# Agent memory in MB
#maestro_nodes::agent::maxmemory: 128

archiva::version: '1.3.6'
activemq::max_memory: '64'

# Archiva repository
maestro_nodes::repositories::host: 'localhost'

# Demo compositions configuration
maestro_demo::archiva_host: 'localhost'
maestro_demo::jenkins_host: 'localhost'
maestro_demo::sonar_host: 'localhost'

# LDAP configuration
#
# maestro::maestro::ldap:
#   hostname: 'ldap.acme.com'               # The hostname of the ldap server
#   ssl: true                               # use SSL?
#   port: '636'                             # The port of the ldap server
#   dn: 'o=acme'                            # The base dn of the ldap system to start searching for users
#   bind_dn: 'cn=ldapuser,ou=system,o=acme' # the core user used for authentication to the ldap server, must be able to perform the necessary searches
#   bind_password: 'ldapuserpassword'       # password for the bind_dn for the root ldap connection
#   admin_user: 'johndoe'                   # ldap user that will be added as a sysadmin for Maestro

# Update plugin versions if needed
# maestro::plugins::irc: '1.2'
# maestro::plugins::continuum: '1.5'
# maestro::plugins::scm: '1.0'
# maestro::plugins::jenkins: '1.1.2'
# maestro::plugins::jira: '1.0'
# maestro::plugins::bamboo: '1.1'
# maestro::plugins::fog: '1.3'


# Using an existing Maven repository manager for Maven builds
# maestro_nodes::repositories::maven_mirrors:
#   -
#     id: 'maestro-mirror'
#     url: 'http://maestro.acme.com:8082/archiva/repository/all'
#     mirrorof: 'external:*'

# maestro_nodes::repositories::maven_servers:
#   -
#     id: 'maestro-mirror'
#     username: 'admin'
#     password: 'admin1'
#   -
#     id: 'maestro-deploy'
#     username: 'admin'
#     password: 'admin1'
