---
# Don't modify these values, they get overwritten in each update
# Copy them to common.yaml or other hiera file specific to some nodes %{clientcert}.yaml
# See Puppet Hiera documentation for more detail on config files

maestro::params::repo:
  url: 'https://repo.maestrodev.com/archiva/repository/all'
  username: 'your_username'
  password: 'CHANGEME'


maestro::maestro::master_password: 'maestro'
maestro::maestro::agent_auto_activate: true
maestro::maestro::metrics_enabled: true
# some other default values that can be changed
# maestro::params::db_server_password: 'maestro'
# maestro::params::db_password: 'maestro'
# maestro::params::lucee_password: maestro
# maestro::params::enabled: true
# needs to match password validation rules: 1-24 characters and a numeric value
# maestro::params::admin_password: 'admin1'

maestro::agent::stomp_host: '%{maestro_host}'
maestro::agent::agent_name: '%{hostname}'

archiva::version: '1.3.9'

sonar::context_path: '/sonar'
sonar::version: '3.5.1'

# Jenkins
jenkins_port: "8181"
jenkins::lts: true
jenkins::version: 1.532.2-1.1
jenkins::install_java: false
jenkins::configure_firewall: false
jenkins::config_hash:
  JENKINS_PORT:
    value: "%{hiera('jenkins_port')}"
  JENKINS_ARGS:
    value: --prefix=/jenkins

# Jenkins plugins...
# Need to specify dependencies
# git: 2.0.4
#   dep: git-client: 1.6.4 (docs say 1.6.3)
#   dep: scm-api: 0.2
# nodelabelparameter: 1.5.1
#   dep: token-macro: 1.9
#     dep: none
#   dep: jquery: 1.7.2-1
#     dep: none
# swarm: 1.15
#   dep: none
jenkins::plugin_hash:
  git:
    version: 2.0.4
  git-client:
    version: 1.6.4
  scm-api:
    version: 0.2
  nodelabelparameter:
    version: 1.5.1
  token-macro:
    version: 1.9
  jquery:
    version: 1.7.2-1
  swarm:
    version: 1.15


# Archiva repository
maestro_nodes::repositories::host: '%{maestro_host}'

# Demo compositions configuration
maestro::lucee::is_demo: true
maestro_demo::archiva_host: '%{maestro_host}'
maestro_demo::jenkins_host: '%{maestro_host}'
maestro_demo::sonar_host: '%{maestro_host}'
maestro_demo::sonar_port: 8083
maestro_demo::sonar_context_path: '/sonar'
maestro_demo::jenkins_context_path: '/jenkins'

# Proxy configuration for nginx and Jetty
maestro::maestro::jetty_forwarded: true

# Memory settings
#maestro::maestro::initmemory: '32'
#maestro::maestro::maxmemory: '256'
#maestro::maestro::permsize: '384m'
#maestro::maestro::maxpermsize: '384m'
#archiva::maxmemory: '64'
maestro_nodes::agent::maxmemory: '128'
maestro::agent::maxmemory: '128'

# activemq
activemq::package_type: rpm
activemq::max_memory: 64

# LDAP configuration
#
# maestro::maestro::ldap:
#   hostname: 'ldap.acme.com'               # The hostname of the ldap server
#   ssl: true                               # use SSL?
#   port: '636'                             # The port of the ldap server
#   dn: 'o=acme'                            # The base dn of the ldap system to start searching for users
#   bind_dn: 'cn=ldapuser,ou=system,o=acme' # the core user used for authentication to the ldap server, must be able to perform the necessary searches
#   bind_password: 'ldapuserpassword'       # password for the bind_dn for the root ldap connection
#   admin_user: 'johndoe'                   # ldap user that will be added as a sysadmin for Maestro

# Update plugin and versions if needed
maestro::plugins::plugins:
  'maestro-ant-plugin':
    version: '1.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-archive-plugin':
    version: '1.1.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-bamboo-plugin':
    version: '1.3'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-builtin-images-plugin':
    version: '1.2.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-continuum-plugin':
    version: '1.9'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-cucumber-plugin':
    version: '1.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-flowdock-plugin':
    version: '1.3'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-fog-plugin':
    version: '1.19'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-git-plugin':
    version: '1.4'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-gitblit-plugin':
    version: '1.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-httputils-plugin':
    version: '1.3'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-irc-plugin':
    version: '1.2.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-jenkins-plugin':
    version: '2.3'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-jira-plugin':
    version: '1.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-maven-plugin':
    version: '1.2.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-puppet-plugin':
    version: '1.4'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-rake-plugin':
    version: '1.5'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-rightscale-plugin':
    version: '1.5'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-rpm-plugin':
    version: '1.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-scm-plugin':
    version: '1.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-shell-plugin':
    version: '1.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-ssh-plugin':
    version: '1.5'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-sonar-plugin':
    version: '1.1'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-svn-plugin':
    version: '1.2'
    dir: 'com/maestrodev/maestro/plugins'
  'maestro-tomcat-plugin':
    version: '1.5.1'
    dir: 'com/maestrodev/maestro/plugins'

# Using an existing Maven repository manager for Maven builds
# maestro_nodes::repositories::maven_mirrors:
#   -
#     id: 'maestro-mirror'
#     url: 'http://maestro.acme.com:8082/archiva/repository/all'
#     mirrorof: 'external:*'

# maestro_nodes::repositories::maven_servers:
#   -
#     id: 'maestro-mirror'
#     username: 'admin'
#     password: 'admin1'
#   -
#     id: 'maestro-deploy'
#     username: 'admin'
#     password: 'admin1'

rvm::version: 1.25.14

# Customize NTP servers
# ntp::servers:
#   - '0.europe.pool.ntp.org'
#   - '1.europe.pool.ntp.org'
#   - '2.europe.pool.ntp.org'
